apiVersion: v1
kind: Service
metadata:
  name: {{ include "spiresql.fullname" . }}
  labels:
    {{- include "spiresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "spiresql.selectorLabels" . | nindent 4 }}
