apiVersion: v1
kind: Service
metadata:
  name: {{ include "spiredb.fullname" . }}
  labels:
    {{- include "spiredb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: resp
    - port: {{ .Values.service.dataAccessPort }}
      targetPort: {{ .Values.service.dataAccessPort }}
      protocol: TCP
      name: dataaccess
  selector:
    {{- include "spiredb.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spiredb.headlessServiceName" . }}
  labels:
    {{- include "spiredb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.metadataPort }}
      targetPort: {{ .Values.service.metadataPort }}
      protocol: TCP
      name: metadata
    - port: {{ .Values.service.epmdPort }}
      targetPort: {{ .Values.service.epmdPort }}
      protocol: TCP
      name: epmd
    - port: {{ .Values.service.distPort }}
      targetPort: {{ .Values.service.distPort }}
      protocol: TCP
      name: dist
  selector:
    {{- include "spiredb.selectorLabels" . | nindent 4 }}
