apiVersion: v2
name: spiredb
description: Helm chart for SpireDB - All-in-one Streaming Distributed OLTP Database
type: application
version: 0.1.1
appVersion: "latest"
icon: https://raw.githubusercontent.com/spiredb/spire_charts/main/art/spire-square.png
keywords:
  - database
  - spiredb
  - ai
  - vector
  - paxos
maintainers:
  - name: spiredb
    email: support@spire.zone
sources:
  - https://github.com/spiredb/spiredb
  - https://github.com/spiredb/charts
