apiVersion: v2
name: spiredb
description: A Helm chart for SpireDB, the infrastructure of truth for Enterprise AI.
type: application
version: 0.1.0
appVersion: "latest"
icon: https://raw.githubusercontent.com/spiredb/spire_charts/main/art/spire-square.png
keywords:
  - database
  - spiredb
  - ai
  - vector
  - paxos
maintainers:
  - name: spiredb
    email: support@spire.zone
sources:
  - https://github.com/spiredb/spiredb
  - https://github.com/spiredb/charts
